/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "MIDI1_UART.h"
#include "USB.h"
#include "USB_audio.h"
#include "USB_cdc.h"
#include "USB_hid.h"
#include "USB_midi.h"
#include "USB_pvt.h"
#include "USB_cydmac.h"
#include "USB_msc.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "Em_EEPROM.h"
#include "CapSense_CompCH0.h"
#include "CapSense_IdacCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IntClock.h"
#include "MIDI1_UART_IntClock.h"
#include "USB_Dm_aliases.h"
#include "USB_Dm.h"
#include "USB_Dp_aliases.h"
#include "USB_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

